# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  appbundle.moduleList:
      class: AppBundle\Admin\moduleAdmin
      arguments: [~, AppBundle\Entity\moduleList, ~]
      tags:
          - { name: sonata.admin, manager_type: orm, label: Modulos, group: Módulos & Aulas }
      public: true

  appbundle.aulaList:
      class: AppBundle\Admin\aulaAdmin
      arguments: [~, AppBundle\Entity\aulaList, ~]
      tags:
          - { name: sonata.admin, manager_type: orm, label: Aulas, group: Módulos & Aulas }
      public: true
